name: MultiPolarCurrency
version: 0.1.7
main: com.brandon.multipolarcurrency.MultiPolarCurrencyPlugin
api-version: "1.21"

commands:
  currency:
    description: Currency management
    usage: /currency <list|info|create|delete>
    permission: multipolarcurrency.admin

  balance:
    description: Check balances
    usage: /balance [CODE]
    aliases: [bal, money]

  mint:
    description: Mint currency into wallet (backing checked)
    usage: /mint <CODE> <amount>

  wallet:
    description: Convert wallet balance <-> physical notes/coins
    usage: /wallet <balance|withdraw|deposit> [CODE] [amount]
    aliases: [w]

permissions:
  multipolarcurrency.admin:
    default: op
