name: MultiPolarCurrency
version: 0.1.6
main: com.brandon.multipolarcurrency.MultiPolarCurrencyPlugin
api-version: "1.21"

commands:
  currency:
    description: Manage currencies
    usage: /currency <list|info|create|delete>
    permission: multipolarcurrency.admin
    permission-message: You do not have permission.

  balance:
    description: View currency balances
    usage: /balance [currency]
    aliases: [bal]

  mint:
    description: Mint currency (commodity-backed consumes backing items)
    usage: /mint <code> <amount> [player]

permissions:
  multipolarcurrency.admin:
    default: op