name: MultiPolarCurrency
version: 0.1.3
main: com.brandon.multipolarcurrency.MultiPolarCurrencyPlugin
api-version: "1.21"

commands:
currency:
  description: Currency management
  usage: /currency <list|info|create|delete>
  permission: multipolarcurrency.admin

  balance:
    description: Check balances
    usage: /balance [CODE]
    aliases: [bal, money]

  mint:
    description: Coin Management
    usage: /mint

permissions:
  multipolarcurrency.admin:
    default: op